apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "security-shepherd-pvc.fullname" . }}-mysql
  labels:
    {{- include "security-shepherd-pvc-mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
