apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "security-shepherd.fullname" . }}-web
  labels:
    {{- include "security-shepherd.labels" . | nindent 4 }}
data:
  conf: |
    {{ toPrettyJson .Values.web.conf | nindent 4 }}
